### ISSUE TITLE
Track page view not accurate

### ISSUE THREAD

**Issue by clinton9ice** [JoaoPedroAS51/nuxt-mixpanel#1]
This is showing that i am currently on claims page and my initial page is claims which is wrong, i don't know it's watching my route update, but my initial is actually correct cause i was on claims page but my current is now supposed to be plans page cause that is the page i am currently on, but i think same value for both until i refresh the entire app before it can create another record and now show that my current is now on plans page.

<img width="1251" alt="err" src="https://github.com/user-attachments/assets/0a2f473b-6b54-4d3c-9137-e98735b20e53">

**Comment by JoaoPedroAS51** [comment]
Hi! Thank you for reporting. I'll take a look :)

**Comment by JoaoPedroAS51** [comment]
Fixed in [v0.0.13](https://github.com/JoaoPedroAS51/nuxt-mixpanel/releases/tag/v0.0.13)
